## Лабораторная работа №3

### Тарасенко Андрей, БПМ161, Вариант 23

#### Задание 3.1.23

Дана система уравнений Ax = b порядка n = 5. Исследовать зависимость погрешности решения x от
погрешностей правой части системы b. $$a_{ij} = \frac{11.7}{(1+c)^7}$$

In [1]:
import numpy as np
import copy

In [2]:
#Зададим матрицу А и вектор b
n = 5 
N = 23

def c(i, j):
    return 0.1*N*i*j

A = np.array([[11.7 / ((1 + c(i, j))**7) for i in range(n)] for j in range(n)])
b = np.array([float(N) for i in range(n)])
print(A)
print(b)

[[1.17000000e+01 1.17000000e+01 1.17000000e+01 1.17000000e+01
  1.17000000e+01]
 [1.17000000e+01 2.74529034e-03 6.77438185e-05 6.09250961e-06
  1.01855541e-06]
 [1.17000000e+01 6.77438185e-05 1.01855541e-06 7.52235550e-08
  1.13128949e-08]
 [1.17000000e+01 6.09250961e-06 7.52235550e-08 5.16377993e-09
  7.47521400e-10]
 [1.17000000e+01 1.01855541e-06 1.13128949e-08 7.47521400e-10
  1.06106811e-10]]
[23. 23. 23. 23. 23.]


In [3]:
#Найдем решение с помощью функции np.linalg.solve
x = np.linalg.solve(A, b)
print(x.reshape(5, 1))

[[ 1.96581197]
 [-0.        ]
 [-0.        ]
 [ 0.        ]
 [-0.        ]]


In [4]:
#Найдем число обусловленности
cA = np.linalg.cond(A)
print(cA)

341005172334.97076


In [5]:
#Найдем вектор d, вектор относительных погрешностей
delta = 1e-4
d = np.zeros(n)

for i in range(n):
    b1 = b.copy()
    b1[i] += delta
    x1 = np.linalg.solve(A, b1)
    d[i] = np.linalg.norm(x - x1, np.inf) / np.linalg.norm(x, np.inf)
print(d.reshape(5,1))

[[5.89243363e-06]
 [1.53410334e+02]
 [3.03958283e+04]
 [3.16752714e+05]
 [2.86510296e+05]]


In [6]:
#Найдем компонентыъу, оказывающую наибольшее влияние на погрешность решения
print('Номер = ', np.argmax(d) + 1)
print('Значение = ', np.max(d))

Номер =  4
Значение =  316752.71357452014


In [7]:
#Вычислим теоретическую погрешность решения и сравним ее с практической
th = cA * delta
print(th)
print(np.max(d) < th)

34100517.233497076
True


Теоретическая погрешность больше практической, как и должно было получиться, так как теор. погр. - оценка сверху.

#### Задание 3.3.6

Дана матрица A. Найти число обусловленности матрицы, используя вычислительный
эксперимент.

In [8]:
#Исходная матрица А
A = np.array([[611, 196, -192, 407],
              [196, 899, 113, -192],
              [-192, 113, 899, 196],
              [407, -192, 196, 611]])
print(A)

[[ 611  196 -192  407]
 [ 196  899  113 -192]
 [-192  113  899  196]
 [ 407 -192  196  611]]


In [9]:
#Зададим 4 линейно-независимых вектора
n = 4
b = np.eye(4)
print(b)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
#Решим систему
x = np.array([np.linalg.solve(A, b[i]) for i in range(n)])
print(x)

[[ 0.04059321 -0.01979786  0.01979398 -0.03961087]
 [-0.01979786  0.01090224 -0.00991408  0.01979398]
 [ 0.01979398 -0.00991408  0.01090224 -0.01979786]
 [-0.03961087  0.01979398 -0.01979786  0.04059321]]


In [11]:
#Найдем нормированное отношение
nA = np.array([np.linalg.norm(x[i]) / np.linalg.norm(b[i]) for i in range(n)])
print(nA.reshape(4, 1))

[[0.06325019]
 [0.03163708]
 [0.03163708]
 [0.06325019]]


In [12]:
#Найдем норму обратной матрицы
obrnA = np.max(nA)
print(obrnA)

0.06325019067480653


In [13]:
#Найдем число обусловленности
cA = np.linalg.norm(A) * obrnA
print(cA)

109.93530906959117
